name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  server-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        working-directory: ./apps/server
        run: pnpm build

      - name: Lint
        working-directory: ./apps/server
        run: pnpm lint

  mobile-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Lint
        working-directory: ./apps/mobile
        run: pnpm lint

  mobile-android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build
        working-directory: ./apps/mobile
        run: eas build --local --platform android --profile development --non-interactive

  mobile-ios-build:
    runs-on: macos-15
    env:
      EAS_LOCAL_BUILD_SKIP_CLEANUP: 1
      EAS_LOCAL_BUILD_WORKINGDIR: ${{ github.workspace }}/.eas-local-build-workingdir
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ${{ env.EAS_LOCAL_BUILD_WORKINGDIR }}/build/apps/mobile/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('apps/mobile/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Cache Xcode derived data
        uses: actions/cache@v4
        with:
          path: ${{ env.EAS_LOCAL_BUILD_WORKINGDIR }}/build/apps/mobile/ios/build
          key: ${{ runner.os }}-xcode-deriveddata-${{ hashFiles('apps/mobile/ios/*.xcodeproj/project.pbxproj', 'apps/mobile/ios/*.xcworkspace/contents.xcworkspacedata') }}
          restore-keys: |
            ${{ runner.os }}-xcode-deriveddata-

      - name: Install Fastlane
        shell: bash
        run: sudo gem install fastlane

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build
        working-directory: ./apps/mobile
        run: eas build --local --platform ios --profile development --non-interactive
